### ISSUE TITLE
Agent startup fails unless did:cheqd is removed from setup.ts

### ISSUE THREAD

**Issue by warren-gallagher** [animo/openid4vc-playground#17]

**Comment by TimoGlastra** [comment]
Could you describe what the issue is? I think it may be an issue that was also fixed in 0.5.1 related to initialization of the Cheqd SDK

**Comment by warren-gallagher** [comment]
I believe the original issue is going, however startup with cheqd still fails because I don't have access to the cheqd test network. I suppose that is not an issue with the software, but perhaps it should be called out in the README.md.
